name: MRA Tasks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: mra/_alternatives to mister/MRA-Alternatives_MiSTer/releases/
      run: ./.github/mister_alternatives.sh