name: Trigger Databases

on:
  gollum:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

    - name: Trigger jtcores
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: update jtcores
        repo: jotego/jtcores_mister
        ref: refs/heads/main
        token: ${{ secrets.JTBIN_UPDATER }}
